version: '3.8'

services:
  storage-node:
    container_name: storage-node
    build:
      context: .
      dockerfile: storage-node/Dockerfile
    depends_on:
      - rollup-node
    networks:
      - app-network
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MASTER=http://rollup-node:3000
      - VIRTUAL_HOST=node1.sd-test.zeropool.network
      - LETSENCRYPT_HOST=node1.sd-test.zeropool.network
      - LETSENCRYPT_EMAIL=mail@test.com

  rollup-node:
    container_name: rollup-node
    build:
      context: .
      dockerfile: rollup-node/Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - VIRTUAL_HOST=rollup.sd-test.zeropool.network
      - LETSENCRYPT_HOST=rollup.sd-test.zeropool.network
      - LETSENCRYPT_EMAIL=mail@test.com

  client-app:
    container_name: client-app
    build:
      context: .
      dockerfile: client-app/Dockerfile
      args:
        - PUBLIC_ROLLUP_API_URL=http://127.0.0.1:3000
        - PUBLIC_NODE_API_URL=http://127.0.0.1:3001
    ports:
      - "3002:3002"
    networks:
      - app-network
    environment:
      - MASTER=http://rollup-node:3000

networks:
  app-network:
    driver: bridge
