version: '3.8'

services:
  # Reverse Proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh

  # Services
  storage-node:
    container_name: storage-node
    restart: always
    build:
      context: .
      dockerfile: storage-node/Dockerfile
    depends_on:
      - rollup-node
    networks:
      - app-network
    environment:
      - PORT=3001
      - MASTER=http://rollup-node:3000

  rollup-node:
    container_name: rollup-node
    restart: always
    build:
      context: .
      dockerfile: rollup-node/Dockerfile
    networks:
      - app-network
    environment:
      - PORT=3000

  client-app:
    container_name: client-app
    restart: always
    build:
      context: .
      dockerfile: client-app/Dockerfile
      args:
        # ! Replace with proper domain names
        - PUBLIC_ROLLUP_API_URL=https://insideout.codes/api/rollup
        - PUBLIC_NODE_API_URL=https://insideout.codes/api/storage
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=insideout.codes
      - LETSENCRYPT_HOST=insideout.codes
      - LETSENCRYPT_EMAIL=mail@test.com

volumes:
  vhost:
  html:
  certs:
  acme:
  conf:


networks:
  app-network:
    driver: bridge
